import type { Metadata } from "next";
import "./globals.css";
import './styles/index.scss';
import AppHeader from '@/components/AppHeader/AppHeader';
import { Nunito } from 'next/font/google';

const nunito = Nunito({
  subsets: ['latin'], // Вказуємо підмножину для латинських символів
  weight: ['400', '500', '700', '200', '800', '900'], // Вибираємо ваги (400 = normal, 700 = bold)
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.className}`}
      >
        <AppHeader />
        {children}
      </body>
    </html>
  );
}
